# database/seed_data.py

import sqlite3

DB_PATH = "activities.db"

def seed_data():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    activities = [
        (
            "NOVA Cybersecurity Lab",
            "Network Security, Privacy, Passwords, Social Engineering",
            "Students will be able to explain how to engage in positive, safe, legal, and ethical behavior when using technology, including social interactions online or when using networked devices.",
            "Integrate quantitative or technical information expressed in words in a text with a version of that information expressed visually.",
            "Computer/laptop or mobile device, Internet connection",
            75,
            None,
            "Intermediate",
            "Online, Individual, Game",
            "intermediate, online, individual, game, network security, privacy, passwords, social engineering, lab",
            "https://thinktv.pbslearningmedia.org/resource/nvcy-sci-cyberlab/nova-cybersecurity-lab/nova-premium-collection/"
        ),
        (
            "Space Shelter",
            "Passwords, Authentication, Phishing, Social Engineering",
            "Students will be able to create a strong, complex password, identify the different methods of two-factor authentication, and identify phishing emails and messages.",
            "Digital Citizenship, K-12 Cybersecurity Standards, ISTE Standards",
            "Computer/laptop or mobile device, Internet connection",
            30,
            45,
            "Beginner",
            "Online, Individual, Game",
            "beginner, online, individual, game, passwords, authentication, two-factor authentication, phishing, social engineering",
            "https://games.gamindo.com/videogames/google/1/?https://games.gamindo.com/videogames/google/"
        ),
        (
            "Gandalf AI",
            "AI Security, Prompt Injection, LLM Vulnerabilities",
            "Students will be able to define prompt injection and explain why it is a cybersecurity risk in AI systems.",
            "UNESCO, CSTA, K-12 3B-NI-04, ISTE Standards",
            "Computer/laptop, Internet connection",
            60,
            None,
            "Advanced",
            "Online, Individual, Game",
            "advanced, online, individual, game, ai, artificial intelligence, prompt injection, llm, vulnerability",
            "https://gandalf.lakera.ai/intro"
        ),
        (
            "CryptoHack",
            "Cryptography",
            "Students will be able to apply foundational cryptography concepts and use Python to manipulate and analyze data.",
            "NIST, AES",
            "Computer/laptop, CryptoHack account, Python environment, Internet connection",
            60,
            None,
            "Advanced",
            "Online, Individual, CTF Platform",
            "advanced, online, individual, ctf platform, cryptography, python, encryption",
            "https://cryptohack.org/"
        ),
        (
            "Interland",
            "Online Safety, Digital Citizenship, Privacy, Phishing, Social Engineering, Passwords",
            "Students will be able to identify phishing scams and unsafe downloads, demonstrate strategies for protecting personal information online, recognize characteristics of strong passwords, and apply responsible digital citizenship behaviors.",
            "CSTA, NICE",
            "Computer/laptop, Internet connection",
            30,
            45,
            "Beginner",
            "Online, Individual, Game",
            "beginner, online, individual, game, online safety, digital citizenship, privacy, phishing, social engineering, passwords",
            "https://beinternetawesome.withgoogle.com/en_us/interland/"
        ),
        (
            "Impersonation & Identity Theft",
            "Privacy",
            "Students will be able to define impersonation and identity theft, reflect on the potential impacts of someone else using your identity, and review strategies for securing information online.",
            "ISTE, K-12 Cybersecurity Standards",
            "Lesson slides, Unsecured accounts handout",
            30,
            None,
            "Intermediate",
            "In-Person, Group, Lesson and Discussion",
            "intermediate, in-person, group, lesson, discussion, privacy, impersonation, identity theft, slides, handout",
            "https://www.commonsense.org/education/digital-citizenship/lesson/impersonation-and-identity-theft"
        ),
        (
            "Being Aware of What You Share",
            "Online Safety, Digital Citizenship, Privacy",
            "Students will be able to reflect on the concept of privacy, analyze different ways that advertisers collect information to send users targeted ads, and identify strategies for protecting their privacy, such as opting out of specific features and analyzing app policies.",
            "Common Core ELA, ISTE, CASEL, AASL",
            "Lesson slides, Ad detective handout, Lesson quiz",
            50,
            None,
            "Beginner, Intermediate",
            "In-Person, Group, Lesson and Discussion",
            "beginner, intermediate, in-person, group, lesson, discussion, quiz, online safety, digital citizenship, privacy, targeted advertising, handout, slides",
            "https://www.commonsense.org/education/digital-citizenship/lesson/being-aware-of-what-you-share"
        ),
        (
            "Guess the Object: Thinking Like AI",
            "Artificial Intelligence, Computer Vision",
            "Students will be able to understand how computer vision systems identify objects based on physical characteristics rather than function, practice computational thinking skills such as abstraction and decomposition, and recognize differences between human reasoning and AI-based object recognition.",
            "ISTE, K-12 Cybersecurity Standards",
            "Object cards, Open space for group play",
            60,
            90,
            "Beginner",
            "In-Person, Group, Card Game",
            "beginner, in-person, group, card game, ai, artificial intelligence, computer vision, object recognition, computational thinking",
            "https://pa-gov.libguides.com/ld.php?content_id=76709554"
        ),
        (
            "Facing Off With Facial Recognition",
            "Digital Citizenship, Artificial Intelligence, Privacy",
            "Students will be able to understand what facial recognition is and consider the benefits and risks of facial recognition technology.",
            "ISTE, K-12 Cybersecurity Standards",
            "Lesson slides and handout",
            20,
            None,
            "Beginner, Intermediate",
            "In-Person, Group, Lesson and Discussion",
            "beginner, intermediate, in-person, group, lesson, discussion, facial recognition, digital citizenship, ai, artificial intelligence, privacy, slides, handout",
            "https://www.commonsense.org/education/digital-citizenship/lesson/facing-off-with-facial-recognition"
        ),
        (
            "Hack-A-Cat: Your Cybersecurity Adventure",
            "Digital Citizenship, Phishing, Social Engineering",
            "Students will be able to recognize phishing attempts and define and identify ransomware and VPNs.",
            "ISTE, K-12 Cybersecurity Standards",
            "Computer/laptop, Internet connection",
            30,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, digital citizenship, phishing, social engineering, ransomware, vpn",
            "https://training.knowbe4.com/modstore/view/4be6a93b-b380-4e5a-934a-27b12674d841"
        ),
        (
            "AI Safety for Students",
            "AI Safety",
            "Students will be able to explain what artificial intelligence (AI) is and navigate the digital world safely while benefiting from AI capabilities.",
            "ISTE, K-12 Cybersecurity Standards",
            "Computer/laptop, Internet connection",
            30,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, ai, artificial intelligence, ai safety",
            "https://training.knowbe4.com/modstore/view/faf8def0-1248-4f50-a171-634fa207f1ac"
        ),
        (
            "Building a Cypher Disk",
            "Cryptography",
            "Students will be able to understand the basic concepts of encryption and decryption using a substitution cipher, apply problem-solving and pattern recognition skills to decrypt messages made by others, and recognize the role of cryptography in cybersecurity.",
            "Cryptography (CRY), NICE",
            "Scissors, a brad, markers, pages T50-T51",
            40,
            60,
            "Beginner, Intermediate",
            "In-Person, Individual or Group, Hands-On Activity",
            "beginner, intermediate, in-person, individual or group, hands-on, activity, cryptography, encryption, decryption, substitution cipher, handout",
            "https://cyber.org/news/classroom-activity-building-cypher-disk"
        ),
        (
            "Denial-of-Service Attack Group Activity",
            "Malware, Cyber Threats",
            "Students will be able to execute a denial-of-service attack on a model of a computer network, determine quantitative metrics that measure the impact of a DDoS attack, and design and test a solution to prevent a DDoS attack on a model of a computer network.",
            "Next Generation Science Standards MS-ETS1-3, MS-ETS1-4",
            "Timer, 9x12 colored construction paper, scissors, server queue handout, processing paper handout, clear tape, boxes to collect cards, permanent marker, pen/pencil per participant",
            60,
            None,
            "Intermediate",
            "In-Person, Group, Hands-On Activity",
            "intermediate, in-person, group, hands-on, activity, ddos, denial of service, malware, cyber threats, network attack",
            "https://www.sciencebuddies.org/teacher-resources/lesson-plans/cybersecurity-denial-of-service#summary"
        ),
        (
            "316ctf: CTF",
            "Cryptography, Network Security",
            "Students will be able to apply cybersecurity problem-solving skills to identify vulnerabilities, decode encrypted information, and analyze network data, and practice common cybersecurity tools and techniques such as password cracking, cryptographic decoding, and network investigation.",
            "K-12 Cybersecurity Standards - CRY, Network Security (NET), NICE",
            "Computer/laptop, Internet connection, 316ctf account, cybersecurity tools like Wireshark, John The Ripper, Linux virtual machine",
            45,
            60,
            "Advanced",
            "Online, Individual, CTF Platform",
            "advanced, online, individual, ctf platform, cryptography, network security, encryption, password cracking, vulnerability, wireshark",
            "https://316ctf.com/"
        ),
        (
            "KC7 Cyber Detective",
            "Malware, Cyber Threats, Incident Response",
            "Students will be able to use SQL queries to examine how logs work, identify what attackers do, determine where to look for evidence, and develop judgment and pattern recognition skills.",
            "NICE, NIST",
            "Computer/laptop, Internet connection",
            30,
            60,
            "Beginner, Intermediate, Advanced",
            "Online, Individual, Game",
            "beginner, intermediate, advanced, online, individual, game, malware, cyber threats, incident response, sql, log analysis, digital forensics",
            "https://kc7cyber.com/"
        ),
        (
            "Threats to Networks Game Idea",
            "Network Security, Cyber Threats, MITM, Packet Sniffing, DoS",
            "Students will be able to recognize network vulnerabilities and understand how networks transmit data.",
            "CSTA 2-NI-2",
            "Rope or tape lines, envelopes, binder clips, notecards",
            30,
            None,
            "Beginner",
            "In-Person, Group, Hands-On Activity",
            "beginner, in-person, group, hands-on, activity, network security, cyber threats, mitm, man-in-the-middle, packet sniffing, dos, denial of service",
            "https://sites.google.com/view/nifty-assignments/home/2021/unplug-the-internet"
        ),
        (
            "CMD Challenge",
            "Operating Systems, Command Line",
            "Students will be able to navigate a file system using basic command line commands and practice executing commands such as listing files, changing directories, and manipulating files.",
            "K-12 Cybersecurity Standards, Computer Science Standards",
            "Computer/laptop, Internet connection",
            45,
            None,
            "Intermediate",
            "Online, Individual, Game",
            "intermediate, online, individual, game, command line, operating system, os, cli, terminal",
            "https://cmdchallenge.com/"
        ),
        (
            "Amanita Whitehat 1 & 2",
            "Malware, Cyber Threats, Social Engineering",
            "Students will be able to identify common cyber threats such as malware, phishing, and suspicious downloads, and respond to potential cybersecurity risks.",
            "K-12 Cybersecurity Standards, NICE",
            "Computer/laptop, Internet connection",
            45,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, puzzle, malware, cyber threats, social engineering, phishing, suspicious downloads",
            "https://cryptologicfoundation.org/resources/cyber-games/amanita-whitehat-2/"
        ),
        (
            "OverTheWire: Bandit",
            "Operating Systems, Command Line",
            "Students will be able to develop foundational Linux command line skills, navigate files and read file contents, search for information using terminal commands, and apply problem-solving skills to progress through challenges.",
            "K-12 Cybersecurity Standards, NICE",
            "Computer/laptop, Internet connection, terminal or SSH client",
            45,
            60,
            "Advanced",
            "Online, Individual, CTF Platform",
            "advanced, online, individual, ctf platform, operating system, linux, command line, cli, ssh, terminal",
            "https://overthewire.org/wargames/"
        ),
        (
            "TryCyber Challenges",
            "Malware, Cyber Threats, Network Security",
            "Students will be able to explore real-world cybersecurity tasks such as investigating cyber incidents and identifying potential threats, and develop problem-solving and analytical skills while learning how to respond to security events.",
            "K-12 Cybersecurity Standards, NICE",
            "Computer/laptop, Internet connection",
            30,
            45,
            "Intermediate",
            "Online, Individual, Scenario-Based Game",
            "intermediate, online, individual, scenario-based game, malware, cyber threats, network security, incident response",
            "https://trycyber.us/challenges/"
        ),
        (
            "AI Problem Solvers Challenge",
            "Artificial Intelligence",
            "Students will be able to recognize that AI is a tool that follows human-created instructions, practice designing prompts using a four-step process, collaborate with peers to solve concrete problems, reflect on ethical and responsible uses of AI, and recognize how clarity, iteration, and ethical framing improve the usefulness of AI outputs.",
            "ISTE, K-12 Cybersecurity Standards",
            "Computer/laptop or tablet, Internet connection, whiteboard (optional)",
            60,
            None,
            "Beginner, Intermediate",
            "In-Person or Online, Group, Activity",
            "beginner, intermediate, in-person or online, group, activity, ai, artificial intelligence, prompt engineering, ai ethics, collaboration, slides",
            "https://drive.google.com/file/d/1Z5HMA82WlKhCcEUQxR_7c1XnElYXIgJG/view"
        ),
        (
            "Mix & Move with AI",
            "Artificial Intelligence",
            "Students will be able to explore three creative stages, using AI prompts to spark inspiration and coding concepts to customize their final project.",
            "ISTE AI Standards",
            "Computer/laptop, Internet connection",
            60,
            90,
            "Beginner, Intermediate",
            "Online, Individual, Activity",
            "beginner, intermediate, online, individual, activity, ai, artificial intelligence, prompt engineering, creative coding",
            "https://studio.code.org/courses/mix-move-ai-2025/units/1/lessons/1/levels/1"
        ),
        (
            "Cyber Videos + Morris Worm",
            "Cryptography",
            "Students will be able to explore concepts such as layering, information hiding, encapsulation, modularity, domain separation, and process isolation.",
            "K-12 Cybersecurity Standards, Computer Science Standards",
            "Computer/laptop, Internet connection, Headphones",
            30,
            60,
            "Beginner",
            "Online, Individual, Video and Game",
            "beginner, online, individual, video, game, cryptography, worm, encapsulation, modularity, domain separation, process isolation",
            "https://cybercamp.seas.gwu.edu/online-cybercamp-for-middle-school-girls/"
        ),
        (
            "Information Security & The CIA Triad Lessons & Activities",
            "Phishing, Social Engineering, Privacy, Personal Data Protection",
            "Students will be able to explain confidentiality, integrity, and availability (CIA Triad) as the foundation of information security, explore how phishing attacks, fake social media accounts, ransomware, and identity theft can violate the CIA Triad, and describe security controls that can be used to protect computing resources.",
            "APCSP Standards",
            "Slides, Activities, paper, pencils",
            100,
            150,
            "Intermediate",
            "In-Person, Group, Lesson and Activity",
            "intermediate, in-person, group, lesson, activity, discussion, cia triad, confidentiality, integrity, availability, information security, phishing, social engineering, privacy, data protection, handout, slides",
            "https://clark.center/details/rmckernan/ba7c2e5a-dd09-404a-8cdc-9b2f6c205b48"
        ),
        (
            "Personal Data Vulnerabilities Lessons & Activities",
            "Personal Data Protection",
            "Students will be able to explain what a vulnerability is and how vulnerabilities impact cybersecurity, identify elements of their personal data which may be vulnerable to attack, and explain why keeping data safe is important both personally and for professional organizations.",
            "APCSP Standards",
            "Computer/laptop, Internet connection, Activity paper, Documents",
            60,
            120,
            "Intermediate",
            "Online, Individual or Group, Lesson and Activity",
            "intermediate, online, individual or group, lesson, activity, personal data, data vulnerabilities, cybersecurity, safety",
            "https://clark.center/details/rmckernan/1a83d86a-ff12-4812-b6b0-a038b2655201"
        ),
        (
            "Identity, Authentication, Authorization Lessons & Activities",
            "Passwords, Authentication",
            "Students will be able to understand ways in which attackers gain unauthorized access to systems and data, distinguish between authentication and authorization, identify three types of multifactor authentication (knowledge, possession, inherence), and describe what defines a strong password.",
            "APCSP Standards",
            "Computer/laptop, Internet connection",
            100,
            150,
            "Intermediate",
            "In-Person, Group, Lesson and Activity",
            "intermediate, in-person, group, lesson, activity, identity, authentication, authorization, mfa, multi-factor authentication, passwords, strong passwords",
            "https://clark.center/details/rmckernan/10335dd7-1a0f-4f51-895b-8a3f4f181ef8"
        ),
        (
            "Risk Lesson & Activities",
            "Risk Identification and Management",
            "Students will be able to summarize security and privacy risks from collecting and storing personal data on a computer system.",
            "APCSP Standards",
            "Scenario sheets and charts",
            45,
            60,
            "Intermediate",
            "In-Person, Group, Lesson and Activity",
            "intermediate, in-person, group, lesson, activity, discussion, risk management, risk identification, security, privacy, personal data, handout",
            "https://clark.center/details/rmckernan/f55d44e2-14d1-4360-8c8f-7b8357e4386f"
        ),
        (
            "Secure Networking Lesson & Activities",
            "Network Architecture and Attacks",
            "Students will be able to explain network attacks and analyze the ethical considerations and consequences dealt to attackers.",
            "APCSP Standards",
            "Scenario sheets and charts, Counters or 40 pieces of square cardboard cutouts for each student",
            150,
            None,
            "Beginner, Intermediate",
            "In-Person, Group, Lesson and Activity",
            "beginner, intermediate, in-person, group, lesson, activity, discussion, network architecture, network attacks, cyber ethics",
            "https://clark.center/details/rmckernan/eed866c2-1363-4cfd-9e68-fed79ada3096"
        ),
        (
            "Don't Feed the Phish",
            "Phishing, Social Engineering",
            "Students will be able to compare and contrast identity theft with other kinds of theft and describe different ways that identity theft can occur online.",
            "Common Core ELA, ISTE, CASEL, AASL",
            "Colored markers or highlighters, Pencils, Paper, Lesson handouts",
            45,
            None,
            "Beginner",
            "In-Person, Pairs, Hands-On Activity",
            "beginner, in-person, pairs, hands-on, activity, phishing, identity theft, social engineering, lesson, handout",
            "https://www.commonsense.org/education/digital-citizenship/lesson/dont-feed-the-phish"
        ),
        (
            "Password Security Activity and Posters",
            "Strong Password Structure and Creation",
            "Students will be able to engage in creative and critical thinking to explore the concepts behind what makes a strong password.",
            "CSTA K-12 Computer Science Standards, ISTE Standards for Students, Common Core ELA",
            "Lesson poster, Paper, Pencil",
            15,
            None,
            "Beginner",
            "In-Person, Individual or Group, Hands-On Activity",
            "beginner, in-person, individual or group, hands-on, activity, discussion, password security, strong passwords, poster",
            "https://stopthinkconnect.org/campaigns/cybersmart-classroom-activities-posters"
        ),
        (
            "Safe Online Surfing by the FBI",
            "Online Safety, Personal Information Protection",
            "Students will be able to identify and explain the most common dangers of the internet, including phishing emails and the dangers of cookies.",
            "ISTE Standards for Students",
            "Computer/laptop, Internet connection",
            15,
            20,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, online safety, phishing, cookies, personal information protection",
            "https://sos.fbi.gov/en/"
        ),
        (
            "Cyber Land",
            "Firewalls, Computer Configuration, Cyber Careers, Online Safety, Cyber Ethics and Law, Digital Forensics, Malware, Computer Networks, Secure Coding, Public Wi-Fi, Phishing, Ciphers and Codes, IoT",
            "Students will be able to identify and explain a variety of cybersecurity concepts including how firewalls operate, packet filtering, password strength, substitution ciphers and encryption, phishing identification, malware types, and network topologies.",
            "UK National Curriculum / GCSE Computer Science, Cyber Choices / NCA Framework",
            "Computer/laptop, Internet connection",
            10,
            60,
            "Beginner, Intermediate, Advanced",
            "Online, Individual, Game",
            "beginner, intermediate, advanced, online, individual, game, firewalls, network configuration, online safety, cyber ethics, digital forensics, malware, computer networks, secure coding, public wi-fi, phishing, cipher, iot, internet of things",
            "https://cybergamesuk.com/cyber-city"
        ),
        (
            "CyberSafe: Home Sweet Hmm",
            "Digital Literacy, Digital Citizenship, Online Safety",
            "Students will be able to understand the importance and benefits of the internet in everyday life, identify and avoid common cybersecurity risks, protect the privacy of personal information, advocate for help from trusted adults when unsure or uncomfortable, and build awareness among families about their role in making the internet safer.",
            "K-12 Cybersecurity Standards, Computer Science Standards",
            "Computer/laptop, Internet connection, Minecraft Education (download at aka.ms/download)",
            60,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, minecraft, digital literacy, digital citizenship, online safety, privacy awareness",
            "https://education.minecraft.net/en-us/lessons/cybersafe-home-sweet-hmm"
        ),
        (
            "CloudCraft",
            "Digital Identity, Digital Literacy, Digital Communication, Digital Security, Digital Safety, Digital Society",
            "Students will be able to understand how data centers help society manage online identities with integrity, explain how digital media is managed through data centers, describe how data centers defend digital identity, identify how data centers detect and manage digital dangers, and understand the opportunities and impact data centers have on society and the environment.",
            "K-12 Cybersecurity Standards, Computer Science Standards",
            "Computer/laptop, Internet connection, Minecraft Education (download at aka.ms/download)",
            60,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, minecraft, digital identity, digital literacy, digital communication, digital security, digital safety, data center",
            "https://education.minecraft.net/en-us/lessons/cloudcraft"
        ),
        (
            "CyberSafe: Privacy Prodigy",
            "Digital Literacy, Digital Citizenship, Online Safety",
            "Students will be able to keep login information private, discuss real-world cybersecurity problems and strategies for protecting personal information, explain how physical and digital security measures protect electronic information, manage social media use to maintain privacy, and apply safe and responsible practices while participating in online environments.",
            "K-12 Cybersecurity Standards, Computer Science Standards",
            "Computer/laptop, Internet connection, Minecraft Education (download at aka.ms/download)",
            60,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, minecraft, privacy, digital literacy, digital citizenship, online safety, personal information protection, responsible use",
            "https://education.minecraft.net/en-us/lessons/privacy-prodigy"
        ),
        (
            "Cyber Threat Defender",
            "Network Infrastructure, Attack and Defense Strategies",
            "Students will be able to identify common cyber threats and attack techniques, analyze network and system data to detect potential security incidents, apply defensive strategies to mitigate and respond to cyber threats, and develop critical thinking and decision-making skills in simulated cybersecurity scenarios.",
            "ISTE, K-12 Cybersecurity Standards",
            "CTD: Digital version can be downloaded to PC and Mac. Physical version uses the CIAS Launcher: https://cias.utsa.edu/ctd/play-online/",
            60,
            150,
            "Intermediate, Advanced",
            "Online or In-Person, Individual or Group, Game",
            "intermediate, advanced, online or in-person, individual or group, game, card game, network infrastructure, cyber threats, attack and defense, incident response",
            "https://cias.utsa.edu/ctd/#elementor-toc__heading-anchor-2"
        ),
        (
            "AI for Oceans",
            "Artificial Intelligence, Machine Learning, Data Classification",
            "Students will be able to explain how AI systems learn from data, identify how classification models are trained and improved, and recognize bias and errors in AI systems.",
            "ISTE AI Standards, CSTA, K-12 Cybersecurity Standards",
            "Computer/laptop or tablet, Internet connection",
            60,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Activity",
            "beginner, intermediate, online, individual, activity, ai, artificial intelligence, machine learning, data classification, bias",
            "https://curriculum.code.org/pwc/ayp/8/"
        ),
        (
            "Enter the Spudnet",
            "Network Security, Internet Infrastructure, Cyber Threats",
            "Students will be able to understand how data travels across networks, identify basic network components and vulnerabilities, and apply strategic thinking to defend against cyber attacks.",
            "K-12 Cybersecurity Standards, CSTA",
            "Board game set (cards, tokens, game board), Group play space",
            60,
            90,
            "Beginner, Intermediate",
            "In-Person, Group, Board Game",
            "beginner, intermediate, in-person, group, board game, hands-on, network security, internet infrastructure, cyber threats",
            "https://potatopirates.game/products/enter-the-spudnet-family-board-games"
        ),
        (
            "Understanding Password Reuse, Variations & Multi-Factor Authentication Risks",
            "Passwords, Authentication",
            "Students will be able to explain credential stuffing and the risks of password reuse and variation, describe multi-factor authentication (MFA) and its protections as well as key vulnerabilities such as adversary-in-the-middle, push fatigue, session theft, and fallback method weaknesses, assess and improve personal password and authentication practices, and reflect on personal risk.",
            "CSTA K-12 Computer Science Standards (3A-CS-02, 3B-CS-03), NICE SP & PR: K0001, K0002, K0003, ISTE Standards",
            "Computer/device for teacher to present questions, The Guardian article, MFA bypass risks article, Forbes 'How Hackers Bypass MFA' article",
            60,
            None,
            "Intermediate",
            "In-Person, Group, Reading and Discussion",
            "intermediate, in-person, group, reading, discussion, activity, passwords, mfa, multi-factor authentication, credential stuffing, password reuse, authentication risk",
            "https://annmichaelsen.com/2025/09/17/lesson-plan-understanding-password-reuse-variations-multi-factor-authentication-risks/"
        ),
        (
            "Protecting Data Lesson Plan",
            "Authentication, Privacy, Personal Data Protection",
            "Students will be able to discuss the benefits of computer virus scanning software and the need for regular updates, explain the benefits of multi-factor authentication, and respond thoughtfully to a stimulus question.",
            "CSP Conceptual Framework: IOC 2, CSTA K-12: NI",
            "Slides, Reading handout",
            45,
            None,
            "Intermediate",
            "In-Person, Group, Lesson and Discussion",
            "intermediate, in-person, group, lesson, discussion, activity, data protection, mfa, multi-factor authentication, antivirus, reading, handout, slides",
            "https://studio.code.org/courses/csp-2021/units/10/lessons/10"
        ),
        (
            "Privacy & Security Lessons",
            "Authentication, Personal Data Protection",
            "Students will be able to use multi-factor authentication to protect an account, apply strategies to password-protect data, identify phishing and malware threats, understand how digital footprints are created, manage personal data to reduce their digital footprint, and assess whether data collected by websites and apps is essential to its stated purpose.",
            "K-12 Cybersecurity Standards",
            "Computer/device, Internet connection (additional resources listed at the link)",
            45,
            60,
            "Intermediate, Advanced",
            "In-Person, Group, Lesson and Activity",
            "intermediate, advanced, in-person, group, lesson, activity, discussion, privacy, security, mfa, multi-factor authentication, phishing, malware, digital footprint, authentication, personal data",
            "https://curriculumstagingbos.azurewebsites.net/media/7494/years_7-8_classroom_ideas-privacy_and_security.pdf"
        ),
        (
            "Operating Systems & Security Settings",
            "Operating Systems",
            "Students will be able to explain how operating systems provide security, locate key security settings on their devices, evaluate current security configurations, and adjust settings to improve device protection.",
            "K-12 Cybersecurity Standards",
            "Computer/device, Internet connection, Handout",
            45,
            60,
            "Intermediate, Advanced",
            "In-Person, Group, Lesson and Activity",
            "intermediate, advanced, in-person, group, lesson, activity, discussion, operating system, os, security settings, device security, configuration, handout",
            "https://www.cs.purdue.edu/outreach/docs/indiana-4565-pdfs/unit2/day7lessonplan_operatingsystemsandsecuritysettings.pdf"
        ),
        (
            "Cybersecurity & Digital Safety Lesson Plan",
            "Passwords, Personal Data Protection, Social Engineering, Malware, Online Safety",
            "Students will be able to understand digital safety and explore topics such as passwords, personal data protection, social engineering, malware, and online safety.",
            "K-12 Cybersecurity Standards",
            "Slides, Discussion questions",
            50,
            60,
            "Beginner",
            "In-Person, Group, Lesson and Discussion",
            "beginner, in-person, group, lesson, discussion, digital safety, online safety, passwords, personal data protection, social engineering, malware, slides",
            "https://cyberama.org/gallery/Lesson%20Plan%20for%20Teachers.pdf"
        ),
        (
            "Viruses & Malware 101 Lesson Plan",
            "Malware, Cyber Threats",
            "Students will be able to identify signs that a computer may be infected with malicious software, protect their computer using antivirus and antispyware software, define viruses, spyware, and Trojans, avoid inadvertently downloading malicious software, and use antivirus software effectively.",
            "CSTA K-12 Cybersecurity Standards (2-CS-03, 3A-CS-02), ISTE Standards, Cyber.org Standards",
            "AVAST antivirus software, Video",
            90,
            None,
            "Intermediate, Advanced",
            "Online or In-Person, Individual, Lesson and Activity",
            "intermediate, advanced, online or in-person, individual, lesson, activity, video, virus, malware, antivirus, antispyware, trojan, malicious software",
            "https://www.denverlibrary.org/sites/dplorg/files/Viruses%20and%20Malware%20101%20Lesson%20Plan%2012-1-13.docx"
        ),
        (
            "Cyber Threats & Protection: Cybersecurity Escape Room Activity",
            "Malware, Phishing",
            "Students will be able to identify common cyber threats and explain strategies for protecting their devices, accounts, and personal data.",
            "CSTA K-12 Standards, ISTE, NICE",
            "Computer/laptop, Internet connection, Escape room form link, Handout",
            60,
            90,
            "Intermediate",
            "In-Person, Individual, Activity",
            "intermediate, in-person, individual, activity, escape room, malware, phishing, cyber threats, personal data protection, handout",
            "https://www.cs.purdue.edu/outreach/docs/indiana-4565-pdfs/unit2/day3lessonplan_cyberthreatsandprotection.pdf"
        ),
        (
            "Cybersecurity - Digital Forensics Games",
            "Digital Forensics, Malware, Privacy, Personal Data Protection",
            "Students will be able to explain the purpose of digital forensics and its role in investigating cybercrime, identify and describe the steps involved in a digital forensics investigation (collection, analysis, preservation), analyze digital evidence to determine how a cyber incident occurred, and evaluate system vulnerabilities and propose ways to prevent future cyberattacks.",
            "CSTA K-12 Standards",
            "Computer/laptop, Internet connection",
            30,
            None,
            "Beginner, Intermediate",
            "Online, Individual, Game",
            "beginner, intermediate, online, individual, game, digital forensics, malware, privacy, personal data protection, cybercrime investigation",
            "https://www.legendsoflearning.com/learning-objectives/cybersecurity-digital-forensics/"
        )
    ]

    cursor.executemany("""
    INSERT INTO activities (
        title, topic, learning_objectives, standards, materials, min_time_minutes, max_time_minutes, difficulty, activity_type, tags, link
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, activities)

    conn.commit()
    conn.close()

    print("\n Activity data inserted!\n")

if __name__ == "__main__":
    seed_data()
